server {
    listen 80;
    listen 443 ssl;
    server_name localhost; # Ajusta esto si usas un dominio local como magento.test

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /var/www/html/pub; # Magento sirve desde la carpeta /pub

    index index.php;

    client_max_body_size 100M; # Aumenta el tamaño máximo de subida

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php-fpm:9000; # Nombre del servicio PHP-FPM en docker-compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
